config/routes.rb
Lanparty::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

	scope '(:locale)', locale: /en|nl/ do

		resources :blog_posts do
			resources :blog_comments
		end

		resources :orders do
			resources :order_items do
				post 'scan', on: :collection
				post 'add', on: :collection
			end

			patch 'place', on: :member
			patch 'pay', on: :member
		end

		resources :clans

		resources :store_item_classes

		resources :pricing_defaults

		resources :store_item_pricing_overrides

		resources :store_item_class_pricing_overrides

		resources :user_groups

		resources :logs

		resources :sponsors

		get 'user/edit', to: 'users#edit', as: :edit_current_user

		get 'signup', to: 'users#new', as: :signup

		get 'logout', to: 'sessions#destroy', as: :logout

		get 'login', to: 'sessions#new', as: :login

		scope controller: :pages, as: :pages do
			get 'info', to: :info
			get 'location', to: :location
			get 'faq', to: :faq
			get 'contact', to: :contact
			get 'signup_finished', to: :signup_finished
			get 'darules', to: :rules, as: :rules
			get 'admin', to: :admin
		end

		scope 'dynamic_scripts', as: :dynamic_scripts do
			get 'datatables', to: 'dynamic_scripts#datatables', as: :datatables
		end

		namespace 'util' do
			get 'soundtest', to: 'soundtest#soundtest', as: :soundtest
			get 'order_check', to: 'order_check#order_check', as: :order_check
		end

		resources :teams do
			patch :join, on: :member
			patch :leave, on: :member
		end

		resources :sessions

		resources :users do
			post :markpayed, on: :collection
			get :soundtest, on: :collection
		end

		resources :match_lose_links

		resources :match_win_links

		resources :match_scores

		resources :rounds

		resources :matches

		resources :prices

		resources :games

		resources :compos do
			patch :save_bracket, on: :member
		end

		resources :barcodes

		resources :store_items

		root to: 'pages#home', as: :home
	end

	root to: 'pages#home'
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	@@access_type_attributes = []

	column_names.each do |col|
		if col.start_with?("access_type_")
			s = col.to_sym
			@@access_type_attributes.push(s)
		end
	end

	validates_uniqueness_of :name
	validates_presence_of :name

	has_and_belongs_to_many :users
	# TODO: I really want this dependent
	has_and_belongs_to_many :pricing_defaults#, :dependent => :destroy

	mount_uploader :badge, BadgeUploader

	def allows_access?(access_type)
		self.send(:"access_type_#{access_type}") or self.allows_access_transitively?(access_type)
	end

	def self.access_type_attributes()
		@@access_type_attributes
	end

	protected
	@@implied_by = { }

	def self.is_implied_by(one, other)
		if @@implied_by.has_key?(one)
			@@implied_by[one].push(other)
		else
			@@implied_by[one] = [other]
		end
	end

	def self.get_implications(one)
		result = @@implied_by[one]
		return result.nil? ? [] : result
	end

	def self.implies(one, other)
		is_implied_by(other, one)
	end

	def allows_access_transitively?(access_type)
		self.class.get_implications(access_type).any? { |atype| self.allows_access?(atype) }
	end

	# used for testing
	def self.remove_implications
		@@implied_by = {}
	end

	implies :user_editing, :user_detail_viewing
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
	before_filter :login_required
	before_filter { access_required :user_editing }
	before_action :setup_environment, only: [:show, :edit, :update, :destroy]

	# GET /user_groups
	# GET /user_groups.json
	def index
		@user_groups = UserGroup.all
	end

	# GET /user_groups/1
	# GET /user_groups/1.json
	def show
	end

	# GET /user_groups/new
	# GET /user_groups/new.json
	def new
		@user_group = UserGroup.new
	end

	# GET /user_groups/1/edit
	def edit
	end

	# POST /user_groups
	# POST /user_groups.json
	def create
		@user_group = UserGroup.new(user_group_params)

		if @user_group.save
			redirect_to user_groups_url, flash: { info: 'User group was successfully created.' }
		else
			render action: "new"
		end
	end

	# PUT /user_groups/1
	# PUT /user_groups/1.json
	def update
		if @user_group.update(user_group_params)
			redirect_to user_groups_url, flash: { info: 'User group was successfully updated.' }
		else
			render action: "edit"
		end
	end

	# DELETE /user_groups/1
	# DELETE /user_groups/1.json
	def destroy
		@user_group.destroy

		redirect_to user_groups_url
	end

	private

	def setup_environment
		@user_group = UserGroup.find(params[:id])
	end

	def user_group_params
		# TODO: Should do real permission checking. Not doing this now because i need column info
		# params.require(:user_group).permit(:description, :name, :badge, ...access type columns)
		params.require(:user_group).permit!
	end
end

app/views/user_groups/_form.html.erb
<%= simple_form_for(@user_group) do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<% UserGroup.access_type_attributes.each do |group_attr| %>
		<%= f.input group_attr %>
	<% end %>
	<%= f.input :badge %>
	<%= f.submit class: "btn btn-default" %>
<% end %>

app/views/user_groups/edit.html.erb
<% title t(:edit, model: t("user_group.one")) %>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path, class: "btn btn-default" %>

app/views/user_groups/index.html.erb
<% title t("user_group.other") %>

<table class="table">
	<tr>
		<th><%= t("simple_form.labels.user_group.badge") %></th>
		<th><%= t("simple_form.labels.user_group.name") %></th>
		<th><%= t("simple_form.labels.user_group.description") %></th>
		<th class="action-column"></th>
	</tr>

	<% @user_groups.each do |user_group| %>
		<tr>
			<td><%= image_tag user_group.badge_url(:badge) if user_group.badge_url(:badge) %></td>
			<td><%= user_group.name %></td>
			<td><%= user_group.description %></td>
			<td class="action-column"><%= standard_edit_buttons(user_group) %></td>
		</tr>
	<% end %>
</table>

<%= link_to t(:new, model: t("user_group.one")), new_user_group_path, class: "btn btn-default" %>

app/views/user_groups/new.html.erb
<% title t(:new, model: t("user_group.one")) %>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path, class: "btn btn-default" %>

app/views/user_groups/show.html.erb
<p>
	<b>Name:</b>
	<%= @user_group.name %>
</p>

<p>
	<b>Description:</b>
	<%= @user_group.description %>
</p>


<%= link_to t(:edit), edit_user_group_path(@user_group), class: "btn btn-default" %> |
<%= link_to 'Back', user_groups_path, class: "btn btn-default" %>