config/routes.rb
Lanparty::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

	scope '(:locale)', locale: /en|nl/ do

		resources :blog_posts do
			resources :blog_comments
		end

		resources :orders do
			resources :order_items do
				post 'scan', on: :collection
				post 'add', on: :collection
			end

			patch 'place', on: :member
			patch 'pay', on: :member
		end

		resources :clans

		resources :store_item_classes

		resources :pricing_defaults

		resources :store_item_pricing_overrides

		resources :store_item_class_pricing_overrides

		resources :user_groups

		resources :logs

		resources :sponsors

		get 'user/edit', to: 'users#edit', as: :edit_current_user

		get 'signup', to: 'users#new', as: :signup

		get 'logout', to: 'sessions#destroy', as: :logout

		get 'login', to: 'sessions#new', as: :login

		scope controller: :pages, as: :pages do
			get 'info', to: :info
			get 'location', to: :location
			get 'faq', to: :faq
			get 'contact', to: :contact
			get 'signup_finished', to: :signup_finished
			get 'darules', to: :rules, as: :rules
			get 'admin', to: :admin
		end

		scope 'dynamic_scripts', as: :dynamic_scripts do
			get 'datatables', to: 'dynamic_scripts#datatables', as: :datatables
		end

		namespace 'util' do
			get 'soundtest', to: 'soundtest#soundtest', as: :soundtest
			get 'order_check', to: 'order_check#order_check', as: :order_check
		end

		resources :teams do
			patch :join, on: :member
			patch :leave, on: :member
		end

		resources :sessions

		resources :users do
			post :markpayed, on: :collection
			get :soundtest, on: :collection
		end

		resources :match_lose_links

		resources :match_win_links

		resources :match_scores

		resources :rounds

		resources :matches

		resources :prices

		resources :games

		resources :compos do
			patch :save_bracket, on: :member
		end

		resources :barcodes

		resources :store_items

		root to: 'pages#home', as: :home
	end

	root to: 'pages#home'
end

app/models/store_item.rb
class StoreItem < ActiveRecord::Base
	has_many :barcodes, dependent: :destroy
	has_many :pricing_overrides, as: :payable, dependent: :destroy
	belongs_to :store_item_class

	validates_presence_of :name, :purchase_price
	validates_uniqueness_of :name, scope: :removed
	validates_presence_of :stock
	validates_numericality_of :stock, only_integer: true, greater_than_or_equal_to: 0
	validates_presence_of :purchase_price
	validates_numericality_of :purchase_price, greater_than_or_equal_to: 0
	validates_presence_of :store_item_class

	default_scope { where(removed: false) }

	def price(user)
		pricing_default = PricingDefault.find_best_pricing_default(user)

		if pricing_default
			calculate_overrides(pricing_default)
		else
			purchase_price
		end
	end

	def calculate_overrides(pricing_default)
		default_price = pricing_default.apply_transform(purchase_price, purchase_price)
		item_pricing_override = pricing_overrides.where(pricing_default: pricing_default).first

		if item_pricing_override
			item_pricing_override.apply_transform(purchase_price, store_item_class.apply_pricing_overrides(pricing_default, purchase_price, default_price))
		else
			store_item_class.apply_pricing_overrides(pricing_default, purchase_price, default_price)
		end
	end
end

app/controllers/store_items_controller.rb
class StoreItemsController < ApplicationController
	before_filter :login_required
	before_filter(except: [:index,:show]) { access_required :store_editing }

	before_action :set_view, only: :index
	before_action :setup_environment, only: [:show, :edit, :update, :destroy]

	def set_view
		session[:store_items_view] = (params[:store_items_view] || session[:store_items_view] || :list).to_sym
	end

	# GET /store_items
	# GET /store_items.json
	def index
		@store_items = StoreItem.all
	end

	# GET /store_items/1
	# GET /store_items/1.json
	def show
	end

	# GET /store_items/new
	# GET /store_items/new.json
	def new
		@store_item = StoreItem.new
	end

	# GET /store_items/1/edit
	def edit
	end

	# POST /store_items
	# POST /store_items.json
	def create
		@store_item = StoreItem.new(store_item_params)

		if @store_item.save
			redirect_to store_items_url, flash: { info: 'StoreItem was successfully created.' }
		else
			render action: "new"
		end
	end

	# PUT /store_items/1
	# PUT /store_items/1.json
	def update
		if @store_item.update(store_item_params)
			redirect_to store_items_url, flash: { info: 'StoreItem was successfully updated.' }
		else
			render action: "edit"
		end
	end

	# DELETE /store_items/1
	# DELETE /store_items/1.json
	# TODO: URGENT!!! DELETING A STORE ITEM SHOULD EITHER NOT BE POSSIBLE OR ORDER ITEMS SHOULD HANDLE THIS
	def destroy
		@store_item.removed = true
		@store_item.save!

		redirect_to store_items_url
	end

	private

	def setup_environment
		@store_item = StoreItem.find(params[:id])
	end

	def store_item_params
		params.require(:store_item).permit(:purchase_price, :name, :stock, :store_item_class_id)
	end
end

app/helpers/store_items_helper.rb
module StoreItemsHelper
	def store_items_view_selector_class(toggles_to)
		session[:store_items_view] == toggles_to ? "btn btn-default active" : "btn btn-default"
	end

	def stock_warning_color(store_item)
		store_item.stock == 0 ? "danger" : "" #store_item.stock < 10 ? "warning" : ""
	end
end

app/views/store_items/_form.html.erb
<%= simple_form_for(@store_item) do |f| %>
	<%= f.input :name %>
	<%= f.input :stock %>
	<%= f.input :purchase_price %>
	<%= f.association :store_item_class %>
	<%= f.submit class: "btn btn-default" %>
<% end %>

app/views/store_items/_store_items_collection.html.erb
<% content_for(:before_title) do %>
    <div class="btn-toolbar game-list-view-options">
        <div class="btn-group">
            <%= link_to content_tag("i", "", class: "fa fa-list"), url_for(store_items_view: :list), class: store_items_view_selector_class(:list) %>
        </div>
    </div>
<% end %>

<%= render partial: (session[:store_items_view] == :list ? "store_items/store_items_list" : "game_grid"),
           locals: { store_items: store_items, render_actions: render_actions } %>

app/views/store_items/_store_items_list.html.erb
<% admin = current_user.access_allowed?(:store_editing) %>
<table class="table table-striped datatable">
	<thead>
	<tr>
		<th><%= t("simple_form.labels.store_item.name") %></th>
		<th><%= t("simple_form.labels.store_item.stock") %></th>
		<th><%= t("simple_form.labels.store_item.price") %></th>
		<% if admin %>
		<th><%= t("simple_form.labels.store_item.purchase_price") %></th>
		<% end %>
		<th class="action-column"></th>
	</tr>
	</thead>

	<tbody>
	<% store_items.each do |store_item| %>
		<tr class="<%= stock_warning_color(store_item) %>">
			<td><%= store_item.name %></td>
			<td><%= store_item.stock %></td>
			<td><%= number_to_currency store_item.price(current_user), unit: "€" %></td>
			<% if admin %>
			<td><%= number_to_currency store_item.purchase_price, unit: "€" %></td>
			<% end %>
			<td class="action-column"><%= render_actions.call(store_item) %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/store_items/edit.html.erb
<% title t(:edit_title, model: t("store_item.one")) %>

<%= render 'form' %>

<%= link_to 'Back', store_items_path %>

app/views/store_items/index.html.erb
<% title t("store_item.other") %>

<%= render partial: "store_items/store_items_collection",
           locals: { store_items: @store_items,
                     render_actions: lambda { |store_item| standard_edit_buttons(store_item) if current_user.access_allowed? :store_editing } } %>

<%= link_to t(:new, model: t("store_item.one")), new_store_item_path, class: "btn btn-default" %>

app/views/store_items/new.html.erb
<% title t(:new, model: t("store_item.one")) %>

<%= render 'form' %>

<%= link_to 'Back', store_items_path %>

app/views/store_items/show.html.erb
<p>
	<b>Name:</b>
	<%= @store_item.name %>
</p>

<p>
	<b>Buy price:</b>
	<%= @store_item.purchase_price %>
</p>
<fieldset id="barcodes">
	<legend>barcodes</legend>
	<ul>
		<table border="0">
			<% @store_item.barcodes.each do |barcode| %>
				<tr>
					<td><%= link_to barcode.code, barcode %></td>
					<td><%= link_to t(:show), barcode %></td>
					<td><%= link_to t(:edit), edit_barcode_path(barcode) %></td>
					<td><%= link_to t(:destroy), barcode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</table>
		<%= link_to 'Add Barcode', new_barcode_path %>
	</ul>
</fieldset>


<%= link_to t(:edit), edit_store_item_path(@store_item) %> |
<%= link_to 'Back', store_items_path %>