config/routes.rb
Lanparty::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

	scope '(:locale)', locale: /en|nl/ do

		resources :blog_posts do
			resources :blog_comments
		end

		resources :orders do
			resources :order_items do
				post 'scan', on: :collection
				post 'add', on: :collection
			end

			patch 'place', on: :member
			patch 'pay', on: :member
		end

		resources :clans

		resources :store_item_classes

		resources :pricing_defaults

		resources :store_item_pricing_overrides

		resources :store_item_class_pricing_overrides

		resources :user_groups

		resources :logs

		resources :sponsors

		get 'user/edit', to: 'users#edit', as: :edit_current_user

		get 'signup', to: 'users#new', as: :signup

		get 'logout', to: 'sessions#destroy', as: :logout

		get 'login', to: 'sessions#new', as: :login

		scope controller: :pages, as: :pages do
			get 'info', to: :info
			get 'location', to: :location
			get 'faq', to: :faq
			get 'contact', to: :contact
			get 'signup_finished', to: :signup_finished
			get 'darules', to: :rules, as: :rules
			get 'admin', to: :admin
		end

		scope 'dynamic_scripts', as: :dynamic_scripts do
			get 'datatables', to: 'dynamic_scripts#datatables', as: :datatables
		end

		namespace 'util' do
			get 'soundtest', to: 'soundtest#soundtest', as: :soundtest
			get 'order_check', to: 'order_check#order_check', as: :order_check
		end

		resources :teams do
			patch :join, on: :member
			patch :leave, on: :member
		end

		resources :sessions

		resources :users do
			post :markpayed, on: :collection
			get :soundtest, on: :collection
		end

		resources :match_lose_links

		resources :match_win_links

		resources :match_scores

		resources :rounds

		resources :matches

		resources :prices

		resources :games

		resources :compos do
			patch :save_bracket, on: :member
		end

		resources :barcodes

		resources :store_items

		root to: 'pages#home', as: :home
	end

	root to: 'pages#home'
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
	# new columns need to be added here to be writable through mass assignment
	attr_accessor :password
	before_save :prepare_password
	before_save :init_balance

	scope :payed, -> { where("payed = ?", true) }

	validates_presence_of :username, :email
	validates_uniqueness_of :username, :email, allow_blank: true
	validates_format_of :username, with: /\A[-\w\._@]+\z/i, allow_blank: true, message: "should only contain letters, numbers, or .-_@"
	validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
	validates_presence_of :password, on: :create
	validates_confirmation_of :password
	validates_length_of :password, minimum: 4, allow_blank: true

	has_and_belongs_to_many :user_groups
	has_and_belongs_to_many :teams
	belongs_to :clan
	has_many :logs

	# login can be either username or email address
	def self.authenticate(login, pass)
		user = find_by(username: login) || find_by(email: login)
		return user if user && user.password_hash == user.encrypt_password(pass)
	end

	def encrypt_password(pass)
		BCrypt::Engine.hash_secret(pass, password_salt)
	end

	def access_allowed?(access_type)
		allowed = false
		user_groups.find_each do |group|
			allowed ||= group.allows_access?(access_type)
		end
		allowed
	end

	def clan_tag
		clan.try(:tag)
	end

	def clan_tag=(tag)
		self.clan = Clan.find_or_create_by tag: tag if tag.present?
	end

	def self.smsg_generate_checksum val
		mod = val % 97
		return mod == 0 ? 97 : mod
	end

	def structured_message
		id_str = sprintf "%010d", id
		checksum = sprintf "%02d", User.smsg_generate_checksum(id)
		"+++#{id_str[0..2]}/#{id_str[3..6]}/#{id_str[7..9]}#{checksum}+++"
	end

	def self.find_by_structured_message msg
		m = /(?:\+|\*){,3}(\d{3})\/?(\d{4})\/?(\d{3})(\d{2})(?:\+|\*){,3}/.match(msg)

		raise "invalid structured message: #{msg}" if m.nil?

		requested_id = (m[1] + m[2] + m[3]).to_i
		calculated_checksum = smsg_generate_checksum(requested_id)
		message_checksum = m[4].to_i

		raise "wrong structured message checksum in #{msg}: expected #{calculated_checksum}, got #{message_checksum}." if calculated_checksum != message_checksum

		self.find(requested_id)
	end

	def all_badges
		badges = []

		user_groups.each do |user_group|
			badge_url = user_group.badge_url(:badge)
			badges.push(image_url: badge_url, title: user_group.description) if badge_url
		end

		teams.each do |team|
			compo = team.compo
			has_won = compo.has_won?(team)
			badge_url = has_won && compo.winning_badge_url(:badge) || compo.participation_badge_url(:badge)
			badge_title = has_won && "#{compo.game.name} compo winner" || "#{compo.game.name} compo participant"
			badges.push(image_url: badge_url, title: badge_title) if badge_url
		end

		badges
	end

	def init_balance
		self.account_balance ||= BigDecimal.new("0")
	end

	def sound_or_default_name
		if pending_order_sound && self.class.all_sounds.map{|sound| sound[:name]}.include?(pending_order_sound)
			pending_order_sound 
		else
			"Bloom"
		end
	end

	def self.build_sound_info(sound_name)
		{ name: sound_name,
		  files: [{ ext: "mp3", type: "audio/mpeg" },
		          { ext: "wav", type: "audio/wav"}].map do |type_info|
		            { file: sound_name + "." + type_info[:ext],
		              type: type_info[:type] }
			        end }
	end

	def sound_or_default
		self.class.build_sound_info sound_or_default_name
	end

	def self.all_sounds
		%w(Bloom Concern Connected Full Gentle\ Roll High\ Boom Hollow Hope Jump\ Down Jump\ Up Looking\ Down Looking\ Up
		   Nudge Picked Puff Realization Second\ Glance Stumble Suspended Turn Unsure Metal\ Gear\ Solid\ -\ Alert).map { |sound| build_sound_info(sound) }
	end

	private

	def prepare_password
		unless password.blank?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = encrypt_password(password)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :login_required, except: [:new, :create, :index]
	# TODO: Move these checks to strong parameters.
	before_filter(only: [:create]) { true_required !params[:user].has_key?(:user_group_ids) }
	before_filter(only: [:update]) { true_required(!params[:user].has_key?(:user_group_ids) || current_user.access_allowed?(:user_editing)) }
	before_filter(only: [:edit,:update]) { true_required(params[:id] == current_user.id.to_s || current_user.access_allowed?(:user_editing)) }
	before_filter(only: [:markpayed]) { access_required :user_editing }
	before_action :setup_environment, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all.includes(:teams,:user_groups)
	end

	def show
	end

	def new
		if User.count >= $SETTINGS[:max_participants]
			redirect_to root_url, flash: { danger: "Sorry, the lanparty is filled to the brim... :(" }
			return
		end

		@user = User.new
	end

	def create
		if User.count >= $SETTINGS[:max_participants]
			redirect_to root_url, flash: { danger: "Sorry, the lanparty is filled to the brim... :(" }
			return
		end

		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to pages_signup_finished_url, flash: { info: "Thank you for signing up! You are now logged in." }
		else
			render action: 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			if user_params[:clan_tag].empty?
				@user.clan = nil
				@user.save
			end
			redirect_to users_url, flash: { info: "Your profile has been updated." }
		else
			render action: 'edit'
		end
	end

	def markpayed
		@user = User.find_by_structured_message params[:msg]
		if @user.update(payed: true)
			redirect_to users_url, flash: { info: "User has been marked as payed." }
		else
			render action: 'index'
		end
	end

	private

	def setup_environment
		@user = User.find params[:id]
	end

	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation, :password_hash, :password_salt, :clan_tag, :payed, :account_balance, :pending_order_sound, user_group_ids: [])
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def avatar_url user, size = 48
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		"http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
	end
end

app/views/users/_badges.html.erb
<span class="badges">
	<% user.all_badges.each do |badge| %>
		<%= image_tag badge[:image_url], title: badge[:title] %>
	<% end %>
</span>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
	<%= f.input :username %>
	<%= f.input :clan_tag, input_html: { data: { autocomplete_source: Clan.order(:tag).map(&:tag) } } %>
	<%= f.input :payed if logged_in? and current_user.access_allowed?(:user_editing) %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.input :password_confirmation, required: true %>
	<%= f.association :user_groups, multiple: true if current_user and current_user.access_allowed? :user_editing %>
    <%= f.input :account_balance if logged_in? and current_user.access_allowed?(:user_editing) %>
	<%= f.input :pending_order_sound, collection: User.all_sounds.map { |sound| sound[:name] },
	            input_html: { :id => "sound-selector", "data-soundtestpath" => util_soundtest_path } if current_user and current_user.access_allowed? :cashier_service %>
    <%= f.button :submit, (@user.new_record? ? t(".sign_up_btn") : t(".update_btn")) %>
<% end %>
<div id="sound-test-area"></div>

app/views/users/_payed_form.html.erb
<%= form_tag markpayed_users_path do %>
	<%= label_tag :msg, t(".structured_message") %>
	<%= text_field_tag :msg %>
	<%= submit_tag t(".mark_as_payed"), class: "btn btn-default" %>
<% end %>

app/views/users/edit.html.erb
<% title t(:edit_title, model: t("profile.one")) %>

<%= render 'form' %>

app/views/users/index.html.erb
<% title t("participant.other") %>
<% canview = current_user && current_user.access_allowed?(:user_detail_viewing) %>
<% admin = current_user && current_user.access_allowed?(:user_editing) %>
<table class="table table-striped datatable">
	<thead>
	<tr>
		<th class="action-column"></th>
		<th><%= t("simple_form.labels.user.username") %></th>
		<th nowrap><%= t("simple_form.labels.user.badge") %></th>
		<th><%= t("simple_form.labels.user.clan_tag") %></th>
		<th class="visible-md visible-lg"><%= t("simple_form.labels.user.payed") %></th>
		<% if canview %>
			<th class="visible-md visible-lg"><%= t("simple_form.labels.user.email") %></th>
			<th class="visible-md visible-lg"><%= t("simple_form.labels.user.user_groups") %></th>
		<% end %>
		<% if admin %>
			<th class="action-column"></th>
		<% end %>
	</tr>
	</thead>
	<tbody>
	<% @users.each do |user| %>
		<tr class="<%= canview ? (user.payed ? "success" : "danger") : "" %>">
			<td class="action-column"><%= image_tag(avatar_url(user), alt: "Icon") %></td>
			<td><%= user.username %> </td>
			<td nowrap><%= render partial: "badges", locals: { user: user } %></td>
			<td title="<%= user.clan_tag %>" ><%= user.clan.get_view_tag if user.clan %></td>
			<td class="visible-md visible-lg">
				<span class="hide"><%= user.payed %></span><i class="fa <%= user.payed ? "fa-check-square-o" : "fa-square-o" %>"></i>
			</td>
			<% if canview %>
				<td class="visible-md visible-lg"><%= user.email %></td>
				<td class="visible-md visible-lg"><%= user.user_groups.map { |grp| grp.name }.join(", ") %></td>
			<% end %>
			<% if admin %>
				<td class="action-column"><%= standard_edit_buttons(user) %></td>
			<% end %>
		</tr>
	<% end %>
	</tbody>
</table>

<% if admin %>
	<%= link_to t(:new, model: t("user.one")), new_user_path, class: "btn btn-default" %>
	<h4><%= t(".payment_processing") %></h4>
	<%= render 'payed_form' %>
<% end %>

app/views/users/new.html.erb
<% title t(:signup) %>

<p><%= t(:account_already_html, login_link: link_to(t(:login), login_path)) %></p>
<p class="text-warning"><%= t(".warning") %></p>

<%= render 'form' %>

app/views/users/show.html.haml
- title t("profile.one")

= image_tag avatar_url(@user, 128), id: "profile-avatar"
%p
	%b #{t(:username)}:
	= @user.username
	= render partial: "badges", locals: { user: @user }
%p
	%b #{t("clan.one")}:
	= @user.clan.tag if @user.clan
%p
	%b #{t(:email)}:
	= @user.email
- if current_user && (current_user == @user || current_user.access_allowed?(:user_editing))
	%p
		%b #{t("simple_form.labels.user.account_balance")}:
		= number_to_currency @user.account_balance, unit: "€"


#profile-edit-btn
	= link_to t(:edit), edit_user_path(@user), class: "btn btn-default" if current_user and current_user == @user