config/routes.rb
Lanparty::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

	scope '(:locale)', locale: /en|nl/ do

		resources :blog_posts do
			resources :blog_comments
		end

		resources :orders do
			resources :order_items do
				post 'scan', on: :collection
				post 'add', on: :collection
			end

			patch 'place', on: :member
			patch 'pay', on: :member
		end

		resources :clans

		resources :store_item_classes

		resources :pricing_defaults

		resources :store_item_pricing_overrides

		resources :store_item_class_pricing_overrides

		resources :user_groups

		resources :logs

		resources :sponsors

		get 'user/edit', to: 'users#edit', as: :edit_current_user

		get 'signup', to: 'users#new', as: :signup

		get 'logout', to: 'sessions#destroy', as: :logout

		get 'login', to: 'sessions#new', as: :login

		scope controller: :pages, as: :pages do
			get 'info', to: :info
			get 'location', to: :location
			get 'faq', to: :faq
			get 'contact', to: :contact
			get 'signup_finished', to: :signup_finished
			get 'darules', to: :rules, as: :rules
			get 'admin', to: :admin
		end

		scope 'dynamic_scripts', as: :dynamic_scripts do
			get 'datatables', to: 'dynamic_scripts#datatables', as: :datatables
		end

		namespace 'util' do
			get 'soundtest', to: 'soundtest#soundtest', as: :soundtest
			get 'order_check', to: 'order_check#order_check', as: :order_check
		end

		resources :teams do
			patch :join, on: :member
			patch :leave, on: :member
		end

		resources :sessions

		resources :users do
			post :markpayed, on: :collection
			get :soundtest, on: :collection
		end

		resources :match_lose_links

		resources :match_win_links

		resources :match_scores

		resources :rounds

		resources :matches

		resources :prices

		resources :games

		resources :compos do
			patch :save_bracket, on: :member
		end

		resources :barcodes

		resources :store_items

		root to: 'pages#home', as: :home
	end

	root to: 'pages#home'
end

app/models/pricing_default.rb
class PricingDefault < ActiveRecord::Base
	include PricingTransform

	validates_presence_of :transform
	validates_presence_of :name
	validates_presence_of :priority
	validates_uniqueness_of :name

	has_and_belongs_to_many :user_groups
	has_many :pricing_overrides

	def self.find_best_pricing_default(user)
		user.user_groups.map { |group| group.pricing_defaults }.flatten.sort { |pricing1, pricing2| pricing1.priority - pricing2.priority }.first || fallback_default
	end

	def self.fallback_default()
		# TODO: Implement concept of a "fallback default"
		pricingDefault = PricingDefault.find_by name: $SETTINGS[:fallback_pricing_default_name]
		if pricingDefault
			return pricingDefault
		else
			name = $SETTINGS[:fallback_pricing_default_name]
			transform = $SETTINGS[:fallback_pricing_default_transform]
			description = "Price transform used when user does not belong to any group"
			priority = 0
			
			fallbackPricingDefault=PricingDefault.new(
				description:description,
				name:name,
				priority:priority,
				transform:transform
			)
			#save the pricingdefault to the database for future reference.
			fallbackPricingDefault.save!
			return fallbackPricingDefault
		end
	end
end

app/controllers/pricing_defaults_controller.rb
class PricingDefaultsController < ApplicationController
	before_filter :login_required
	before_filter { access_required :store_editing }
	before_action :setup_environment, only: [:show, :edit, :update, :destroy]

	# GET /pricing_defaults
	# GET /pricing_defaults.json
	def index
		@pricing_defaults = PricingDefault.all
	end

	# GET /pricing_defaults/1
	# GET /pricing_defaults/1.json
	def show
	end

	# GET /pricing_defaults/new
	# GET /pricing_defaults/new.json
	def new
		@pricing_default = PricingDefault.new
	end

	# GET /pricing_defaults/1/edit
	def edit
	end

	# POST /pricing_defaults
	# POST /pricing_defaults.json
	def create
		@pricing_default = PricingDefault.new(pricing_default_params)

		if @pricing_default.save
			redirect_to pricing_defaults_url, flash: { info: 'Pricing default was successfully created.' }
		else
			render action: "new"
		end
	end

	# PUT /pricing_defaults/1
	# PUT /pricing_defaults/1.json
	def update
		if @pricing_default.update(pricing_default_params)
			redirect_to pricing_defaults_url, flash: { info: 'Pricing default was successfully updated.' }
		else
			render action: "edit"
		end
	end

	# DELETE /pricing_defaults/1
	# DELETE /pricing_defaults/1.json
	def destroy
		@pricing_default.destroy

		redirect_to pricing_defaults_url
	end

	private

	def setup_environment
		@pricing_default = PricingDefault.find(params[:id])
	end

	def pricing_default_params
		params.require(:pricing_default).permit(:transform, :description, :name, :priority, user_group_ids: [])
	end
end

app/views/pricing_defaults/_form.html.erb
<%= simple_form_for(@pricing_default) do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.association :user_groups, multiple: true %>
	<%= f.input :transform %>
	<%= f.submit class: "btn btn-default" %>
<% end %>

app/views/pricing_defaults/edit.html.erb
<h1>Editing pricing_default</h1>

<%= render 'form' %>

<%= link_to t(:show), @pricing_default %> |
<%= link_to 'Back', pricing_defaults_path %>

app/views/pricing_defaults/index.html.erb
<h1><%= t("pricing_default.other") %></h1>

<table class="table">
	<tr>
		<th><%= t("simple_form.labels.pricing_default.name") %></th>
		<th><%= t("simple_form.labels.pricing_default.description") %></th>
		<th class="action-column"></th>
	</tr>

	<% @pricing_defaults.each do |pricing_default| %>
		<tr>
			<td><%= pricing_default.name %></td>
			<td><%= pricing_default.description %></td>
			<td class="action-column"><%= standard_edit_buttons(pricing_default) %></td>
		</tr>
	<% end %>
</table>

<br/>

<%= link_to t(:new, model: t("pricing_default.one")), new_pricing_default_path, class: "btn btn-default" %>

app/views/pricing_defaults/new.html.erb
<% title t(:new, model: t("pricing_default.one")) %>

<%= render 'form' %>

<%= link_to 'Back', pricing_defaults_path %>

app/views/pricing_defaults/show.html.erb
<p>
	<b>Name:</b>
	<%= @pricing_default.name %>
</p>

<p>
	<b>Description:</b>
	<%= @pricing_default.description %>
</p>

<p>
	<b>Transformation:</b>
	<%= @pricing_default.transform %>
</p>


<%= link_to t(:edit), edit_pricing_default_path(@pricing_default) %> |
<%= link_to 'Back', pricing_defaults_path %>